### ISSUE TITLE
Precompilation Error

### ISSUE THREAD

**Issue by tlaurie99** [sisl/BayesianSafetyValidation.jl#7]
Hey all

I am consistently getting a precompilation error while trying to use juliacall with this package. Specifically I am getting:
[ Info: Precompiling BayesianSafetyValidation [b2459b7e-6b9e-4dd9-9103-ad6e47d39f21] 
WARNING: Method definition vcat(KernelFunctions.ColVecs{T, TX, S} where S where TX<:AbstractArray{T, 2} where T, KernelFunctions.ColVecs{T, TX, S} where S where TX<:AbstractArray{T, 2} where T) in module KernelFunctions at C:\Users\tyler\.julia\packages\KernelFunctions\nkiEB\src\utils.jl:95 overwritten in module BayesianSafetyValidation at C:\Users\tyler\OneDrive\Desktop\BayesianSafetyValidation.jl-main\src\surrogate_model.jl:2.
ERROR: Method overwriting is not permitted during Module precompilation. Use `__precompile__(false)` to opt-out of precompilation.
┌ Info: Skipping precompilation due to precompilable error. Importing BayesianSafetyValidation [b2459b7e-6b9e-4dd9-9103-ad6e47d39f21].
└   exception = Error when precompiling module, potentially caused by a __precompile__(false) declaration in the module.

AttributeError                            Traceback (most recent call last)

```
Cell In[2], line 1
----> 1 jl.Pkg = jl.seval("using BayesianSafetyValidation")

File ~\.julia\packages\PythonCall\Nr75f\src\JlWrap\any.jl:254, in __setattr__(self, k, v)
    252     else:
    253         return
--> 254     self._jl_callmethod($(pyjl_methodnum(pyjlany_setattr)), k, v)
    255 def __dir__(self):
    256     return ValueBase.__dir__(self) + self._jl_callmethod($(pyjl_methodnum(pyjlany_dir)))

AttributeError: Julia: invalid redefinition of constant Main.Pkg
```

Is this something that is on my end or within the repo? Thanks for your help!

edits: couldn't figure out why the text was massive -- silly line.

**Comment by mossr** [comment]
I just pushed a fix that resolves this, let me know if it works for you

**Comment by tlaurie99** [comment]
Yes it is working now! Thank you for your help.

**Comment by mossr** [comment]
Great to hear! Happy to help :)
